export const RECEIVE_GOODS = 'receive_goods'
export const RECEIVE_RATINGS = 'receive_ratings'
export const RECEIVE_SELLER = 'receive_seller'
export const INCREMENT_FOOD_COUNT = 'increment_food_count'
export const DECREMENT_FOOD_COUNT = 'decrement_food_count'